version: '2'

services:
  postgres:
    image: 'postgres:9.6'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
      - '.:/app'
    environment:
      - POSTGRES_PASSWORD=so_wow

  app:
    depends_on:
      - 'postgres'
    build: .
    ports:
      - '6868:3000'
      - '6767:5173'
    volumes:
      - '.:/app'

volumes:
  postgres:
