version: '2'

services:
  postgres:
    image: 'postgres:14'
    volumes:
      - '.:/app'
    tmpfs:
      - '/var/lib/postgresql/data'
    env_file:
      - '.env.test'
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB_NAME}

  app:
    depends_on:
      - 'postgres'
    build: .
    ports:
      - '6868:3000'
      - '6767:5173'
    volumes:
      - '.:/app'
    env_file:
      - '.env.test'
