source 'https://rubygems.org'

gem 'activerecord-import'
gem 'bootsnap'
gem 'carmen'
gem 'couchrest'
gem 'csv'
gem 'devise'
gem 'devise_cas_authenticatable'
gem 'domain_name'
gem 'dotenv-rails'
gem 'http-cookie'
gem 'i18n'
gem 'json_pure'
gem 'mime-types'
gem 'multi_json'
gem 'netrc'
gem 'pg'
gem 'rack'
gem 'rack-cors'
gem 'rails'
gem 'rake'
gem 'rest-client'
gem 'ruby-net-ldap'
gem 'rubyzip'
gem 'sprockets-rails'
gem 'sqlite3'
gem 'unf'
gem 'unf_ext'

group :development, :test, :assets do
  gem 'mini_racer'
  gem 'puma', '~> 6.0'
  gem 'sassc-rails'
  gem 'terser'
end

group :development do
  gem 'bundle-audit'
end
