version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: true

    steps:
      - checkout
      - run:
          name: Setup filesystem
          command: |
            sudo chown -R 1000 .
      - run:
          name: Docker Compose
          command: |
            docker-compose -f docker-compose.test.yml --env-file .env.test up -d
            sleep 60
      - run:
          name: Wait for DB
          command: timeout 5m bash -c "until docker-compose -f docker-compose.test.yml --env-file .env.test exec postgres pg_isready ; do sleep 5 ; done"
      - run:
          name: Tests
          command: docker-compose -f docker-compose.test.yml --env-file .env.test exec app bash -c "cd front && ./deploy.sh && cd .. && bundle install && rake db:drop db:create db:migrate && cd front && ./deploy.sh && cd .. && rspec"
