version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: false

    steps:
      - checkout
      - run:
          name: Setup filesystem
          command: |
            sudo chown -R 1000 .
      - run:
          name: Docker compose
          command: |
            docker compose -f docker/docker-compose.test.yml up -d
      - run:
          name: Wait for migrations
          command: |
            echo "Waiting for migrations to complete..."
            bash -c '
            until docker compose -f docker/docker-compose.test.yml logs app | grep "Database ready and migrated"; do
              echo "Waiting for migrations..."
              sleep 2
            done
            echo "Migrations completed successfully!"
            '
      - run:
          name: Tests
          command: 
            docker compose -f docker/docker-compose.test.yml exec app bash -c "bundle exec rspec"
